Repository telosnetwork/teloscan, pull requests merged in 2022-12, with the labels that each got.

#259 Include release badge to README.md
  README.md
Labels: 📃 Documentation

#261 Dev
  README.md
Labels: 📃 Documentation

#241 Added ERC1155, renamed claim to withdraw, show none on address page, ...
  src/components/Transaction/ERCTransferList.vue
  src/components/Transaction/FragmentListElement.vue
  src/components/Transaction/InternalTxns.vue
  src/components/Transaction/LogsViewer.vue
  src/components/TransferTable.vue
  src/lib/Contract.js
  src/lib/ContractManager.js
  src/lib/abi/signature/events_signatures_overrides.json
  src/lib/abi/signature/functions_signatures_overrides.json
  src/lib/abi/signature/transfer_signatures.js
  src/lib/utils.js
  src/pages/AccountAddress.vue
  src/pages/Transaction.vue
  src/pages/staking/Staking.vue
  src/pages/staking/WithdrawPage.vue
Labels: ✨ Enhancement, 🎯 Feature

#245 #104 | Function interface overhaul
  src/components/ContractTab/ContractInterface.vue
  src/components/ContractTab/FunctionInterface.vue
  src/components/ContractTab/GenericContractInterface.vue
  src/components/ContractTab/function-interface-utils.js
  src/components/inputs/AddressArrayInput.vue
  src/components/inputs/AddressInput.vue
  src/components/inputs/BaseTextInput.vue
  src/components/inputs/BooleanArrayInput.vue
  src/components/inputs/BooleanInput.vue
  src/components/inputs/BytesArrayInput.vue
  src/components/inputs/SignedIntArrayInput.vue
  src/components/inputs/SignedIntInput.vue
  src/components/inputs/StringArrayInput.vue
  src/components/inputs/StringInput.vue
  src/components/inputs/UnsignedIntArrayInput.vue
  src/components/inputs/UnsignedIntInput.vue
  src/components/inputs/input-helpers.js
  src/css/app.sass
  src/pages/AccountAddress.vue
  src/pages/Block.vue
  src/pages/Transaction.vue
  src/pages/demo/DemoIndexPage.vue
  src/pages/demo/inputs/InputsDemo.vue
  src/router/routes.js
  test/components/ContractTab/function-interface-utils.test.js
Labels: ✨ Enhancement
