Repository telosnetwork/teloscan, pull requests merged in 2022-10, with the labels that each got.

#169 APY frontend calculation fix
  src/pages/staking/staking-utils.js
Labels: bug

#165 Tooltip fade fix
  src/boot/q-component-defaults.js
Labels: bug

#153 Erc721 transfers & log events, responsive fixes, more function overrides, refactoring & fixes
  src/components/AddressField.vue
  src/components/ConnectButton.vue
  src/components/ContractTab/GenericContractInterface.vue
  src/components/MethodField.vue
  src/components/Transaction/ERCTransferList.vue
  src/components/Transaction/LogsTable.vue
  src/components/Transaction/LogsTableRow.vue
  src/components/Transaction/LogsViewer.vue
  src/components/Transaction/ParameterList.vue
  src/components/TransactionTable.vue
  src/components/TransferTable.vue
  src/css/app.sass
  src/events_overrides.json
  src/layouts/MainLayout.vue
  src/lib/Contract.js
  src/lib/ContractManager.js
  src/lib/abi/erc1155.js
  src/lib/abi/erc721.js
  src/lib/abi/erc721Metadata.js
  src/lib/abi/index.js
  src/lib/abi/signature/events_signatures_overrides.json
  src/lib/abi/signature/functions_signatures_overrides.json
  src/lib/abi/signature/transfer_signatures.js
  src/lib/abi/supportsInterface.js
  src/lib/erc721.js
  src/lib/functionSignatures.js
  src/lib/utils.js
  src/pages/AccountAddress.vue
  src/pages/Block.vue
  src/pages/Index.vue
  src/pages/Transaction.vue
  src/signatures_overrides.json
Labels: enhancement

#178 Remove repo issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: tech debt

#192 #176 | Fix persistent contract information when changing /address routes
  src/pages/AccountAddress.vue
Labels: 🐛 Bug

#193 #67 | Fix TX page date field width
  src/components/DateField.vue
  src/pages/Transaction.vue
Labels: 🐛 Bug
