Repository telosnetwork/teloscan, pull requests merged in 2023-01, with the labels that each got.

#270 fixed missing contract case on ERCTransfer component
  src/components/Transaction/ERCTransferList.vue
  src/pages/Transaction.vue
Labels: 🐛 Bug

#277 Fix staking page when user is logged into native
  src/pages/staking/StakeForm.vue
  src/pages/staking/Staking.vue
  src/pages/staking/UnstakeForm.vue
  src/pages/staking/WithdrawPage.vue
  src/store/login/getters.js
  src/store/login/state.js
Labels: ✨ Enhancement

#329 328 enable typescript
  .eslintrc.js
  package.json
  quasar.conf.js
  src/store/store-flag.d.ts
  tsconfig.json
  yarn.lock
Labels: 🔧 Tech Debt

#336 Remembering pagination state for tx table
  src/components/TransactionTable.vue
Labels: 🎯 Feature
